### ISSUE TITLE
Time Zone Support Broken

### ISSUE THREAD

**Issue by ramaboo** [jeremyw/stamp#29]
`t = Time.current.stamp('14:00 UTC')` and `t = Time.current.in_time_zone('any time zone').stamp('14:00 UTC')` both return just the time with the string UTC. For some reason UTC is not being parsed correctly and replaced with the actual timezone.

**Comment by ramaboo** [comment]
Even the examples in the readme regarding timezone don't work!! :(

**Comment by jeremyw** [comment]
@ramaboo Can you add a failing test on a branch that reproduces the issue?

**Comment by ramaboo** [comment]
I don't know Minitest (Rspec here). The test is simple though in rails console type:
```
time = Time.utc(2011, 6, 9, 20, 52, 30)
time.stamp("23:59 UTC")             #=> "20:52 PST"
```

And you will see it's broken.

**Comment by jeremyw** [comment]
Here's what I just got:

```
irb(main):002:0> time = Time.utc(2011,6,9,20,52,30)
=> 2011-06-09 20:52:30 UTC
irb(main):003:0> time.stamp("23:59 UTC")
=> "20:52 UTC"
```

I wonder if something is modifying the behavior of the Time class. Are you
in a Rails app? What version of Ruby/Rails?

**Comment by ramaboo** [comment]
Yeah Rails 4.2.6. I get the same thing as you but in your documentation you state the result should be "20:52 PST" not "20:52 UTC" I can't find a way to get `time.stamp('23:59 UTC') to return a string without UTC in it. No matter what I do it never turns UTC to PST or EST, etc.

**Comment by jeremyw** [comment]
That looks like a bad example in the documentation. However, I'm not sure convinced time zones are working correctly. I would expect `stamp` to emit the zone of the time object you're operating on, but that's not happening. It's been a while since I've been in that code, but it appears to use `ENV['TZ']` to determine the current zone, not based on the zone of the time object.

I don't have a ton of time to investigate further right now, but please let me know if you discover anything or come up with a fix.

**Comment by kbrock** [comment]
>require 'active_support/all'
Time.current.stamp("UTC")
# => "EDT"  
Time.current.in_time_zone('MST').stamp("UTC")
# => "UTC"

looks like it probably thinks TimeWithZone is a Date and not a time.
will look into it

**Comment by kbrock** [comment]
also of interest

```ruby
DateTime.now.stamp("UTC")
# => "-04:00"  

require "active_supprt/all"
ActiveSupport::TimeWithZone.send(:include, ::Stamp)
Time.current.in_time_zone('MST').stamp("UTC")
# => "MST"
```
